### ISSUE TITLE
NRC Research Press

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/journals#10]
Check if these all follow the same style: http://www.nrcresearchpress.com/action/showPublications?display=byAlphabet&pubType=journal (seems to be the case for Canadian Journal of Fisheries and Aquatic Sciences and Canadian Geotechnical Journal at a minimum)

**Comment by damnation333** [comment]
All journals have been reviewed, missing ones added.
For future reference the following journals are thematically different to the rest and request different styles: 
- Canadian Journal of Chemistry (like JACS)
- Canadian Journal of Physics (numeric style)
- Canadian Journal of Physiology and Pharmacology (like Journal of Consulting and Clinical Physiology)

**Comment by rmzelle** [comment]
> Check if these all follow the same style: http://www.nrcresearchpress.com/action/showPublications?display=byAlphabet&pubType=journal (seems to be the case for Canadian Journal of Fisheries and Aquatic Sciences and Canadian Geotechnical Journal at a minimum)

libora determined that Canadian Geotechnical Journal didn't share the same format as Canadian Journal of Fisheries and Aquatic Sciences. See https://github.com/citation-style-language/styles/pull/2074

@damnation333, there isn't really a need for the two pull requests to the "styles" repo here, I think. You can just add all the metadata to the "_journals.tab" file, with the appropriate independent-parent for each. That way we can manage and generate all the NRC journals together in one spot.

**Comment by rmzelle** [comment]
> Canadian Journal of Physics

Looks like we're now just missing this one? I'm fine with closing the issue if that's it.

**Comment by damnation333** [comment]
I am glad we're getting this chapter closed soon! :)
Just made the style for Canadian Journal of Physics.

**Comment by rmzelle** [comment]
Closed with #2420.
