### ISSUE TITLE
Reference style for Biotechnologia journal

### ISSUE THREAD

**Issue by bioinfonext** [citation-style-language/journals#113]
Hi
Could your please let me know the CSL for Biotechnologia journal. 
link: http://www.biotechnologia-journal.org/Journal/BioTechnologia-85/Contact

**Comment by POBrien333** [comment]
Please add the requested information you find here into THIS thread.
Please don't make a forum post or a new issue. Just here is fine. Thanks.

https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-csl-styles
