### ISSUE TITLE
AOSIS styles

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/journals#33]
As discussed here: https://github.com/citation-style-language/styles/pull/2496#discussion_r101438751

Check AOSIS journals and make dependents. 
Apparently, 3 variants are in use (APA, Harvard, Vancouver): https://aosis.co.za/about-journals/manuscript-submission-guidelines/#Manuscript-formatting

 - [x]  author-date style (2017, https://github.com/citation-style-language/styles/pull/2496)
 - [x] make AOSIS Vancouver style (2021-03, https://github.com/citation-style-language/styles/pull/5326)
 - [x] dependent styles (2021-03, https://github.com/citation-style-language/journals/pull/116)
 
All journals copied from https://aosis.co.za/journal-collection/ attached as an .xlsx
aosis-journals.xlsx (15/03/2021) [aosis-journals.xlsx](https://github.com/citation-style-language/journals/files/6148367/aosis-journals.xlsx)

**Comment by POBrien333** [comment]
All journals copied from https://aosis.co.za/journal-collection/ attached as an .xlsx
[aosis-journals.xlsx](https://github.com/citation-style-language/journals/files/6143019/aosis-journals.xlsx)

**Comment by POBrien333** [comment]
Hi @adam3smith 
I'm preparing the dependent styles for the AOSIS journals.
They have three styles, the author-date style I made, APA (which is proper APA) and a "Vancouver" style.
Could you check these guidelines and tell me if we have this style or it needs a new independent one?
https://aosis.co.za/documents/Vancouver_Reference_style_guide.pdf

**Comment by adam3smith** [comment]
I don't know for sure -- the 7/3 et al. is the most unusual part (but not that unusual). You could look at _Chest_ or _The New England Journal of Medicine_, both of which look exactly like this at first glance.

**Comment by POBrien333** [comment]
Great.
In that case it would make sense to make a AOSIS specific Vancouver style. Making them all dependent on another journal's style is not ideal. If they change their style all the AOSIS styles would change.

**Comment by adam3smith** [comment]
Agreed, yes.
