### ISSUE TITLE
Generate styles for all Elsevier Spain Journals

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/journals#47]
Via https://github.com/citation-style-language/styles/pull/2784

338 Spanish Elsevier Journals Spreadsheet: [Elsevier Spain.xlsx](https://github.com/citation-style-language/journals/files/1197505/Elsevier.Spain.xlsx) (generated from: http://www.elsevier.es/sitemap.xml)

64 Medical Journals: https://tienda.elsevier.es/revistas

**Comment by rmzelle** [comment]
Closing per https://github.com/citation-style-language/styles/pull/2784#issuecomment-323025712.
