### ISSUE TITLE
Style sheet for computer and chemical engineering 

### ISSUE THREAD

**Issue by shitalamin** [citation-style-language/journals#76]
https://github.com/citation-style-language/journals/blob/6c4fa9a25866c30f1680b5038ac7bf9d280b72aa/elsevier/_journals.tab#L256

**Comment by rmzelle** [comment]
@shitalamin, sorry for never replying to this, but it's unclear to me why you opened this issue. Can you explain?

(I'll close this ticket for now but we can always reopen it if warranted)
